export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';

export const USER_AUTH_REQUEST: 'USER_AUTH_REQUEST' = 'USER_AUTH_REQUEST';
export const USER_AUTH_FAILED: 'USER_AUTH_FAILED' = 'USER_AUTH_FAILED';
export const USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS' = 'USER_AUTH_SUCCESS';

export const USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST' = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED' = 'USER_LOGOUT_FAILED';
export const USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS' = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST' = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_FAILED: 'USER_REGISTER_FAILED' = 'USER_REGISTER_FAILED';
export const USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS' = 'USER_REGISTER_SUCCESS';

export const USER_PASSWORD_PATCH: 'USER_PASSWORD_PATCH' = 'USER_PASSWORD_PATCH';

export const USER_RESET_PASSWORD_REQUEST: 'USER_RESET_PASSWORD_REQUEST' = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_FAILED: 'USER_RESET_PASSWORD_FAILED' = 'USER_RESET_PASSWORD_FAILED';
export const USER_RESET_PASSWORD_SUCCESS: 'USER_RESET_PASSWORD_SUCCESS' = 'USER_RESET_PASSWORD_SUCCESS';

export const CHANGE_USER_REQUEST: 'CHANGE_USER_REQUEST' = 'CHANGE_USER_REQUEST';
export const CHANGE_USER_FAILED: 'CHANGE_USER_FAILED' = 'CHANGE_USER_FAILED';
export const CHANGE_USER_SUCCESS: 'CHANGE_USER_SUCCESS' = 'CHANGE_USER_SUCCESS';